services:
  - type: web
    name: ai-market-research
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
    rootDir: ai_market_research
